### ISSUE TITLE
Show all trades on all markets by default

### ISSUE THREAD

**Issue by snakes-r-us** [dan-da/bitsquare_market#2]
Currently it is not possible to view all trades across all of the markets (showing mainly the trade volume in BTC, as you can with the Bitsquare application). 

Could you make it the default view so that it displays the trade history (BTC volume) for all markets, if a specific market is not selected?

**Comment by dan-da** [comment]
This has been implemented and is default view on live site.

There is one summary page for each supported base currency.   Default is BTC.

Thanks for the suggestion.
