### ISSUE TITLE
Trade notifications

### ISSUE THREAD

**Issue by dan-da** [dan-da/bitsquare_market#3]
This would be a feature where users could enter an email address and receive notifications when a new offer is posted.

To do this on the website would require that we run an external process, eg from cron each minute.   It would also require some type of database to store the email and associated market(s) for notifications.  In turn, we then need a way for users to modify or delete the alerts, which implies some type of authentication system.   

So it quickly gets a bit complicated.

I'm not sure but sending SMS might require some type of paid account.  I think that starting out with email alerts should be sufficient.

There are some privacy implications, as we would now be storing email addresses associated with markets.

So upon review, I think that this feature is easier and better to implement in the Bisq app itself, which has no need of user auth and can easily call a callback when new offers are posted, plus no central place to store user emails.

anyway, I am entering the issue here for the record.

From email discussion:
------

idea gentlemen that having alerts to email or sms for new trades posted cud double to triple the amount of completed transactions thru the bisq client (:

On Thu, Jul 6, 2017 at 4:45 PM, Manfred Karrer wrote:

    yes that is a longer requested feature, though i am too busy with other stuff...

    maybe Dan can deliver something from the markets page?

    > On 06.07.2017, at 20:07, Patrick wrote:
    >
    > Q:could we get alerts for when a new trade is posted for cad/BTC for
    > example? Liquidity is low so it would be cooler just to get an alert when a
    > new offer is posted than running the app all the time as its decently
    > resource-intensive to run

**Comment by ManfredKarrer** [comment]
Yes totally agree. Would be too complicate and a privacy problem. We will put it on our todo list for app features.

**Comment by dan-da** [comment]
not implementing in web ui.   closing.
